import numpy as np
import pandas as pd

from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler


# ============================================================
# REGIME FEATURES
# ============================================================

REGIME_FEATURES = [
    "contracts_growth",
    "turnover_growth",
    "premium_growth",
    "pcr_contracts",
    "contracts_zscore",
    "turnover_zscore",
    "premium_zscore",
]


# ============================================================
# PREPARE FEATURES
# ============================================================

def prepare_regime_features(df):
    """
    Prepare the feature matrix used for market-regime detection.

    Returns
    -------
    feature_data : DataFrame
        Clean observations used by the clustering model.

    X_scaled : ndarray
        Standardized feature matrix.
    """

    feature_data = df[
        ["Date"] + REGIME_FEATURES
    ].copy()

    # Replace infinite values generated by ratios/growth rates.
    feature_data = feature_data.replace(
        [np.inf, -np.inf],
        np.nan
    )

    # We cannot cluster observations containing missing values.
    feature_data = feature_data.dropna().reset_index(drop=True)

    scaler = StandardScaler()

    X_scaled = scaler.fit_transform(
        feature_data[REGIME_FEATURES]
    )

    return feature_data, X_scaled, scaler


# ============================================================
# RUN REGIME MODEL
# ============================================================

def detect_regimes(
    df,
    n_regimes=3,
    random_state=42
):
    """
    Detect recurring market regimes using K-Means clustering.

    Parameters
    ----------
    df : DataFrame
        Output of analytics.prepare_data()

    n_regimes : int
        Number of market regimes.

    random_state : int
        Ensures reproducible clustering.

    Returns
    -------
    result : DataFrame
        Original observations with regime labels.

    model : KMeans
        Fitted clustering model.

    scaler : StandardScaler
        Feature scaler.
    """

    feature_data, X_scaled, scaler = prepare_regime_features(df)

    if len(feature_data) < n_regimes:
        raise ValueError(
            "Not enough observations to create "
            f"{n_regimes} regimes."
        )

    model = KMeans(
        n_clusters=n_regimes,
        random_state=random_state,
        n_init=20
    )

    labels = model.fit_predict(X_scaled)

    feature_data["regime_cluster"] = labels

    return feature_data, model, scaler


# ============================================================
# DESCRIBE REGIMES
# ============================================================

def describe_regimes(
    regime_data,
    original_df
):
    """
    Create an interpretable statistical profile for each
    detected regime.

    The labels are NOT assigned by the ML model itself.
    They are inferred from the characteristics of each cluster.
    """

    merged = regime_data.merge(
        original_df,
        on="Date",
        how="left",
        suffixes=("", "_original")
    )

    summary = (
        merged
        .groupby("regime_cluster")
        .agg(
            observations=("Date", "count"),
            avg_contracts=("index_contracts", "mean"),
            avg_turnover=("index_turnover", "mean"),
            avg_premium=("avg_premium", "mean"),
            avg_pcr=("pcr_contracts", "mean"),
            avg_contracts_growth=("contracts_growth", "mean"),
            avg_turnover_growth=("turnover_growth", "mean"),
            avg_premium_growth=("premium_growth", "mean"),
        )
        .reset_index()
    )

    # --------------------------------------------------------
    # Create interpretable regime descriptions
    # --------------------------------------------------------

    summary["activity_score"] = (
        summary["avg_contracts_growth"].fillna(0)
        + summary["avg_turnover_growth"].fillna(0)
    )

    summary["activity_score"] = (
        summary["activity_score"]
        .rank(method="first")
    )

    # Highest activity → Expansion
    # Lowest activity → Low Activity
    # Middle → Balanced

    sorted_clusters = (
        summary
        .sort_values("activity_score")
        ["regime_cluster"]
        .tolist()
    )

    labels = {}

    if len(sorted_clusters) >= 1:
        labels[sorted_clusters[0]] = "Low Activity"

    if len(sorted_clusters) >= 2:
        labels[sorted_clusters[len(sorted_clusters) // 2]] = (
            "Balanced Activity"
        )

    if len(sorted_clusters) >= 3:
        labels[sorted_clusters[-1]] = "High Activity"

    # Handle any additional clusters generically.
    for cluster in summary["regime_cluster"]:
        if cluster not in labels:
            labels[cluster] = f"Regime {cluster + 1}"

    summary["regime_name"] = (
        summary["regime_cluster"]
        .map(labels)
    )

    return summary


# ============================================================
# ADD REGIMES TO COMPLETE DATASET
# ============================================================

def add_regimes_to_data(
    df,
    n_regimes=3,
    random_state=42
):
    """
    Run regime detection and attach the regime labels
    back to the complete monthly dataset.
    """

    regime_data, model, scaler = detect_regimes(
        df,
        n_regimes=n_regimes,
        random_state=random_state
    )

    summary = describe_regimes(
        regime_data,
        df
    )

    regime_mapping = summary[
        [
            "regime_cluster",
            "regime_name"
        ]
    ]

    result = df.merge(
        regime_data[
            [
                "Date",
                "regime_cluster"
            ]
        ],
        on="Date",
        how="left"
    )

    result = result.merge(
        regime_mapping,
        on="regime_cluster",
        how="left"
    )

    return result, summary, model, scaler